select c.relname as table_name, c.reltuples::bigint as lignes_estimees,
 upper('create') || ' table public.' || quote_ident(c.relname) || E' (\n' || string_agg('  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
 || case when a.attidentity = 'a' then ' generated always as identity' when a.attidentity = 'd' then ' generated by default as identity' else '' end
 || case when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored' when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid) else '' end
 || case when a.attnotnull then ' not null' else '' end, E',\n' order by a.attnum) || E'\n);' as ddl
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
where n.nspname = 'public' and c.relkind in ('r', 'p')
group by c.relname, c.reltuples
order by c.relname;

