select 'sequences' as k, string_agg(format(upper('create') || ' sequence if not exists public.%I as %s start %s increment %s minvalue %s maxvalue %s%s;', s.sequencename, s.data_type, s.start_value, s.increment_by, s.min_value, s.max_value, case when s.cycle then ' cycle' else '' end), E'\n') as v from pg_sequences s where s.schemaname = 'public'
union all select 'sequences_liees', string_agg(format('%s -> %s.%s (%s)', sc.relname, tc.relname, a.attname, dp.deptype::text), E'\n') from pg_depend dp join pg_class sc on sc.oid = dp.objid and sc.relkind = 'S' join pg_namespace n on n.oid = sc.relnamespace and n.nspname = 'public' join pg_class tc on tc.oid = dp.refobjid join pg_attribute a on a.attrelid = tc.oid and a.attnum = dp.refobjsubid where dp.deptype in ('a', 'i')
union all select 'enums', string_agg(format(upper('create') || ' type public.%I as enum (%s);', t.typname, (select string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) from pg_enum e where e.enumtypid = t.oid)), E'\n') from pg_type t join pg_namespace n on n.oid = t.typnamespace where n.nspname = 'public' and t.typtype = 'e'
union all select 'autres_types', string_agg(t.typname || ' (' || t.typtype::text || ')', ', ') from pg_type t join pg_namespace n on n.oid = t.typnamespace where n.nspname = 'public' and t.typtype in ('d', 'c') and not exists (select 1 from pg_class c where c.reltype = t.oid)
union all select 'index', string_agg(pg_get_indexdef(i.indexrelid) || ';', E'\n' order by c.relname) from pg_index i join pg_class c on c.oid = i.indrelid join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and not exists (select 1 from pg_constraint co where co.conindid = i.indexrelid)
union all select 'rls', string_agg(format(upper('alter') || ' table public.%I enable row level security;', c.relname) || case when c.relforcerowsecurity then format(' alter table public.%I force row level security;', c.relname) else '' end, E'\n' order by c.relname) from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and c.relrowsecurity
union all select 'tables_sans_rls', string_agg(c.relname::text, ', ') from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and c.relkind = 'r' and not c.relrowsecurity
union all select 'policies', string_agg(format(upper('create') || ' policy %I on %I.%I as %s for %s to %s%s%s;', p.policyname, p.schemaname, p.tablename, p.permissive, p.cmd, array_to_string(p.roles, ', '), coalesce(' using (' || p.qual || ')', ''), coalesce(' with check (' || p.with_check || ')', '')), E'\n' order by p.schemaname, p.tablename, p.policyname) from pg_policies p where p.schemaname in ('public', 'storage')
union all select 'triggers', string_agg(pg_get_triggerdef(t.oid) || ';', E'\n') from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace where n.nspname in ('public', 'auth', 'storage') and not t.tgisinternal and (n.nspname = 'public' or exists (select 1 from pg_proc p join pg_namespace pn on pn.oid = p.pronamespace where p.oid = t.tgfoid and pn.nspname = 'public'))
union all select 'realtime', string_agg(format(upper('alter') || ' publication supabase_realtime add table %I.%I;', pt.schemaname, pt.tablename), E'\n') from pg_publication_tables pt where pt.pubname = 'supabase_realtime'
union all select 'replica_identity', string_agg(c.relname || ' = ' || c.relreplident::text, ', ') from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and c.relkind = 'r' and c.relreplident <> 'd'
union all select 'droits_tables', string_agg(c.relname || ' (' || c.relkind::text || ') ' || coalesce(c.relacl::text, 'DEFAULT'), E'\n' order by c.relname) from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and c.relkind in ('r', 'v', 'm', 'S')
union all select 'droits_fonctions', string_agg(p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ') ' || coalesce(p.proacl::text, 'DEFAULT'), E'\n' order by p.proname) from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
union all select 'droits_par_defaut', string_agg(pg_get_userbyid(d.defaclrole) || ' ' || coalesce(n.nspname, '*') || ' ' || d.defaclobjtype::text || ' ' || d.defaclacl::text, E'\n') from pg_default_acl d left join pg_namespace n on n.oid = d.defaclnamespace
union all select 'extensions', string_agg(format(upper('create') || ' extension if not exists %I with schema %I; -- %s', e.extname, n.nspname, e.extversion), E'\n') from pg_extension e join pg_namespace n on n.oid = e.extnamespace
union all select 'fonctions_hors_extension', count(*)::text from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
union all select 'agregats_ou_fenetres', string_agg(p.proname::text, ', ') from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.prokind in ('a', 'w')
union all select 'archive_yaounde', string_agg(c.relname::text, ', ') from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'archive_yaounde' and c.relkind = 'r'
union all select 'schemas_cron_net', string_agg(nspname::text, ', ') from pg_namespace where nspname in ('cron', 'net', 'pgmq', 'supabase_functions')
union all select 'buckets', (select string_agg(b.id || ' public=' || b.public, ', ') from storage.buckets b)
union all select 'version_postgres', version();


